lab_1/urls.py
from django.urls import path
from .views import index, friend_list

urlpatterns = [
    path('', index, name='index'),
    # TODO Add friends path using friend_list Views
    path('friends', friend_list)
]

lab_2/urls.py
from django.urls import path
from .views import index, xml, json

urlpatterns = [
    path('', index, name='index'),
    path('xml', xml, name='xml'),
    path('json', json, name='json'),
]

lab_3/urls.py
from django.urls import path
from .views import index, add_friend

urlpatterns = [
    path('', index, name='index'),
    path('add', add_friend)
]

lab_4/urls.py
from django.urls import path
from .views import index, add_note, note_list

urlpatterns = [
    path('', index, name='index'),
    path('add-note', add_note),
    path('note-list', note_list),
]

lab_5/urls.py
from django.urls import path
from .views import index

urlpatterns = [
    path('', index, name='index'),
]

praktikum/urls.py
from django.urls import include, path, re_path
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
from lab_1.views import index as index_lab1

urlpatterns = [
    path('admin/', admin.site.urls, name="admin_url"),
    path('lab-1/', include(lab_1)),
    path('lab-2/', include(lab_2)),
    path('lab-3/', include(lab_3)),
    path('lab-4/', include(lab_4)),
    path('lab-5/', include(lab_5)),
    re_path(r'^$', index_lab1, name='index')
]

lab_1/models.py
from django.db import models

# TODO Create Friend model that contains name, npm, and DOB (date of birth) here
class Friend(models.Model):
    name = models.CharField(max_length=30)
    # TODO Implement missing attributes in Friend model
    npm = models.CharField(max_length=30)
    DOB = models.DateField(max_length=30)
    

lab_2/models.py
from django.db import models

# Create your models here.
class Note(models.Model):
    msg_date = models.DateField()
    msg_to = models.CharField(max_length=30)
    msg_from = models.CharField(max_length=30)
    msg_title = models.CharField(max_length=30)
    msg = models.CharField(max_length=100)

lab_3/models.py
from django.db import models

# Create your models here.

lab_4/models.py
from django.db import models

# Create your models here.

lab_5/models.py
from django.db import models

# Create your models here.

lab_3/forms.py
from lab_1.models import  Friend
from django import forms  

class FriendForm(forms.ModelForm):
    class Meta:
        model = Friend
        fields = ['name', 'npm', 'DOB']

lab_4/forms.py
from lab_2.models import Note
from django import forms  

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['msg_date', 'msg_to', 'msg_from', 'msg_title', 'msg']

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
from .models import Friend

mhs_name = 'Melati Eka Putri'  # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(2002, 3, 25)  # TODO Implement this, format (Year, Month, Date)
npm = 2006464266  # TODO Implement this


def index(request):
    response = {'name': mhs_name,
                'age': calculate_age(birth_date.year),
                'npm': npm}
    return render(request, 'index_lab1.html', response)


def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0


def friend_list(request):
    friends = Friend.objects.all().values()  # TODO Implement this
    response = {'friends': friends}
    return render(request, 'friend_list_lab1.html', response)

lab_2/views.py
from django.http import response
from django.http.response import HttpResponse
from django.core import serializers
from django.shortcuts import render
from .models import Note

# Create your views here.
def index(request):
    notes = Note.objects.all().values()
    msg_number = Note.objects.all().count()
    response = {"notes": notes,
                "num": msg_number,}
    return render(request, 'lab2.html', response)

def xml(request):
    data = serializers.serialize('xml', Note.objects.all())
    return HttpResponse(data, content_type="application/xml")

def json(request):
    data = serializers.serialize('json', Note.objects.all())
    return HttpResponse(data, content_type="application/json")

lab_3/views.py
from lab_3 import admin
from django.shortcuts import redirect, render
from lab_1.models import Friend
from .forms import FriendForm
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url = "/admin/login/")
def index(request):
    friends = Friend.objects.all().values()  # TODO Implement this
    response = {'friends': friends}
    return render(request, 'lab3_index.html', response)

@login_required(login_url = "/admin/login/")
def add_friend(request):
    context = {}
    form = FriendForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        form.save()
        response = redirect('/lab-3')
        return response

    context['form'] = form
    return render(request, "lab3_form.html", context)

lab_4/views.py
from django.shortcuts import render, redirect
from lab_2.models import Note
from .forms import NoteForm

# Create your views here.
def index(request):
    notes = Note.objects.all().values()
    response = {"notes": notes}
    return render(request, 'lab4_index.html', response)

def note_list(request):
    notes = Note.objects.all().values()
    response = {"notes": notes}
    return render(request, 'lab4_note_list.html', response)

def add_note(request):
    context = {}
    form = NoteForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        form.save()
        response = redirect('/lab-4')
        return response

    context['form'] = form
    return render(request, "lab4_form.html", context)

lab_5/views.py
# Create your views here.
from django.shortcuts import render, redirect
from lab_2.models import Note

# Create your views here.
def index(request):
    notes = Note.objects.all().values()
    response = {"notes": notes}
    return render(request, 'lab5_index.html', response)

lab_1/templates/friend_list_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
  </head>
  <body>
    <table>
      <tr>
        <th>Name</th>
        <th>NPM</th>
        <th>DOB</th>
      </tr>
      <!-- TODO loop from Friend model -->
      {% if friends %} 
		    {% for friend in friends %}
        <tr>
			    <td>  {{ friend.name }} </td>
          <td>  {{ friend.npm }} </td>
          <td>  {{ friend.DOB }} </td>
		    </tr>
		    {% endfor %}
	    {% endif %}
    </table>
  </body>
</html>

lab_1/templates/index_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{{ name }}</title>
  </head>
  <body>
    <h1>Hello my name is {{ name }}</h1>
    <article>NPM : {{ npm }}</article>
    <article>I am {{ age }} years old</article>
  </body>
</html>

lab_2/templates/lab2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
  </head>
  <body>
      <!-- TODO loop from Notes model -->
      <h1> 📧 Inbox: {{num}} messages </h1>
      {% if notes %} 
		    {% for note in notes %}
        <h3 style="color:blue"> New Message from {{note.msg_from}}: {{ note.msg_title }} </h1>
			    <p> 🙍‍♀️ To:   {{ note.msg_to }} <br>
              📆 Date: {{ note.msg_date }} </p>
          <p style="background-color:pink"> {{ note.msg }} </p>
		    {% endfor %}
	    {% endif %}
      <!-- END SECTION -->
  </body>
</html>

lab_3/templates/lab3_form.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List Form</title>
  </head>
  <body>
    <h1>💃🕺 Hi, Welcome to Add Friend! 💃🕺</h1> 
    <form action="" method="POST">
        {% csrf_token %}
        <h3> <br> Name <br> <input type="text" name= "name" placeholder="Your Friend Name" maxLength="30" id="id_name"> <br><br>
        NPM <br><input type="text" name= "npm" placeholder="Your Friend NPM" maxLength="30" id="id_npm"> <br><br>
        Date of Birth <br><input type="date" name= "DOB" id="id_DOB"> <br><br>
        <input type="submit" value= "Submit"> </h3>
        <h3><button><a href="/lab-3">Return to Friend List</button></h3> <br><br>
    </form>
  </body>
  <style>
    h1   {
        color: violet;
        background-color: black;
        font-family: verdana;
        padding: 10px; 
        text-align: center}
    h3    {
        font-family: verdana;
        padding: 10px; 
        text-align: center;}
    form {
        background-image: url('https://wallpaperaccess.com/full/1382357.jpg');
    }
    button {
      font-size : 20px;
      background-color: #008CBA;
      color: white;
      padding: 10px;
      border-radius: 12px;
      border: 2px solid black;
      transition-duration: 0.4s;
    }
    button:hover {
      background-color: #bd46b7; 
      color: white;
    }
    a {
        color: white;
        text-decoration: none;
    }
  </style>
</html>

lab_3/templates/lab3_index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
  </head>
  <body>
    <h1>👩‍🦰 Your Friend List 🧑</h1>
    <div class ="table">
    <br><br>
    <table>
      <tr>
        <th>Name</th>
        <th>NPM</th>
        <th>DOB</th>
      </tr>
      <!-- TODO loop from Friend model -->
      {% if friends %} 
		    {% for friend in friends %}
        <tr>
			    <td>  {{ friend.name }} </td>
          <td>  {{ friend.npm }} </td>
          <td>  {{ friend.DOB }} </td>
		    </tr>
		    {% endfor %}
	    {% endif %}
    </table>
    <br><br>
    <h3><button onclick="location.href = '/lab-3/add'">Add Friend</button></h3> <br><br>
    </div>
  </body>
  <style>
    table, th, td {
        border: 2px solid black;
        margin: 2px;
        font-size: 20px;
        font-family: verdana;}
    th, td, h1 {
        padding: 10px;}
    table {
      margin-left: auto;
      margin-right: auto;}
    h1   {
        color: pink;
        background-color: black;
        font-family: verdana;
        padding: 10px; 
        text-align: center}
    .table {
        background-image: url('https://wallpapercave.com/wp/wp2814385.jpg');
    }
    h3 {
      text-align : center;
    }
    button {
      font-size : 20px;
      background-color: #008CBA;
      color: white;
      padding: 10px;
      border-radius: 12px;
      border: 2px solid black;
      transition-duration: 0.4s;
    }
    button:hover {
      background-color: #bd46b7; 
      color: white;
    }
  </style>
</html>

lab_4/templates/lab4_form.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/note_form.css' %}">
</head>
<body>
  <ul>
      <li style="background-color: #111"><a href="add-note">Add Note</a></li>
      <li id ="menu"><a href="note-list">Note List</a></li>
      <li id ="menu"><a href="/lab-4">Note Table</a></li>
  </ul>
  <div class="wrapper">
    <form class="form" action="" method="POST" >
      {% csrf_token %}
      <div class="pageTitle title"> 💌 Add Note 💌 </div>
      <input type="date" class="date formEntry" name="msg_date" placeholder="Date" />
      <input type="text" class="to formEntry" name="msg_to" placeholder="To" />
      <input type="text" class="from formEntry" name="msg_from" placeholder="From"/>
      <input type="text" class="msg_title formEntry" name="msg_title" placeholder="Title"/>
      <textarea class="message formEntry" name="msg" placeholder="Message"></textarea>
      <input class="submit formEntry" type="submit" value= "Submit"> </h3>
    </form>
  </div>
  <script src="app.js"></script>
</body>

</html>

lab_4/templates/lab4_index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Note Data</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/note_table.css' %}">
  </head>
  <body>
    <ul>
      <li id ="menu"><a href="add-note">Add Note</a></li>
      <li id ="menu"><a href="note-list">Note List</a></li>
      <li style="background-color: #111"><a href="/lab-4">Note Table</a></li>
    </ul>
    <h1 class="heading__title">💌 Your Note Table 💌</h1>
    <h3> <br><button class= "submit" onclick="location.href = '/lab-4/add-note'">Add Notes</button></h3> <br>
    <div class ="table">
    <br><br>
    <table>
      <tr>
        <th>Date</th>
        <th>To</th>
        <th>From</th>
        <th>Title</th>
        <th>Message</th>
      </tr>
      {% if notes %} 
		    {% for note in notes %}
        <tr>
			    <td>  {{ note.msg_date }} </td>
          <td>  {{ note.msg_to }} </td>
          <td>  {{ note.msg_from }} </td>
          <td>  {{ note.msg_title }} </td>
          <td>  {{ note.msg}} </td>
		    </tr>
		    {% endfor %}
	    {% endif %}
    </table>
    <br><br>
    </div>
  </body>
</html>

lab_4/templates/lab4_note_list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Note Data</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/note_list.css' %}">
  </head>
  <body>
    <!-- 

GRADIENT BANNER DESIGN BY SIMON LURWER ON DRIBBBLE:
https://dribbble.com/shots/14101951-Banners

-->
  <ul>
    <li id ="menu"><a href="add-note">Add Note</a></li>
    <li style="background-color: #111"><a href="note-list">Note List</a></li>
    <li id ="menu"><a href="/lab-4" name="index">Note Table</a></li>
  </ul>
<div class="main-container">
  <div class="heading">
    <h1 class="heading__title">💌 Your Note Data Card 💌</h1>
    <p class="heading__credits">Design by Melati Eka Putri</p>
  </div>
  <h3><br><button class= "submit" onclick="location.href = '/lab-4/add-note'">Add Notes</button></h3> <br><br>
  <div class="cards">
    {% if notes %} 
		    {% for note in notes %}
        <div class="card card-1">
          <div class="card__icon"><i class="fas fa-bolt"></i></div>
          <p class="card__exit"><i class="fas fa-times"></i></p>
          <p>  </p>
          <h2 class="card__title">{{ note.msg_title}}</h2>
          <p class="card__apply">
            To: {{note.msg_to}} <br> From: {{note.msg_from}} <br> Date: {{note.msg_date}} </p>
          <p class="card__apply" id="msg"><br><br>{{note.msg}}<br><br></p>
        </div>
		    {% endfor %}
	    {% endif %}
  </div>
</div>
  </div>
</div>
  </body>
</html>

lab_5/templates/lab5_index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Note Data</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/note_table.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </head>
  <body>
    <ul>
      <li id ="menu"><a href="add-note">Add Note</a></li>
      <li id ="menu"><a href="note-list">Note List</a></li>
      <li style="background-color: #111"><a href="/lab-4">Note Table</a></li>
    </ul>
    <div class="div1"><h1 class="heading__title">💌 Your Note Table 💌</h1></div>
    <h3> <br><button class= "submit" onclick="location.href = '/lab-4/add-note'">Add Notes</button></h3> <br>
    <div class ="table">
    <br><br>
    <table>
      <tr>
        <th>Date</th>
        <th>To</th>
        <th>From</th>
        <th>Title</th>
        <th>Message</th>
        <th>Actions</th>
      </tr>
      {% if notes %} 
		    {% for note in notes %}
        <tr>
			    <td>  {{ note.msg_date }} </td>
          <td>  {{ note.msg_to }} </td>
          <td>  {{ note.msg_from }} </td>
          <td>  {{ note.msg_title }} </td>
          <td>  {{ note.msg}} </td>
          <td><button class="action" id="view">View</button>
          <button  class="action" onclick="location.href = '/lab-4/add-note'">Edit</button>
          <button  class="action" onclick="location.href = '/lab-4/add-note'">Delete</button></td>
		    </tr>
		    {% endfor %}
	    {% endif %}
    </table>
    <br><br>
    </div>
  </body>
  <style>
      .action {
      width: 100px;
      padding: 10px;
      color: white;
      background-color: #1C0C5B;
      font-size: 15px;
      margin: 2px;
     }
  
    .action:hover {
      border-top: 5px solid #0e3750;
      border-radius: 0%;
      background-color: #A12568;
    }
  </style>
</html>